/**
 * Group Analysis Type Definitions
 * 小组分析类型定义
 *
 * Shared contract between the /api/pool-groups/:id/analysis endpoint (server)
 * and the useGroupAnalysis hook (user-client).
 *
 * Generated by the latent social compatibility pipeline introduced in
 * AI_INTEGRATION_PLAN.md (Phases 1-3).
 */

/**
 * AI-generated explanation for a single user pair within a group.
 * Produced by matchExplanationService.generatePairExplanation().
 *
 * pairKey format: sorted([userId1, userId2]).join('-')
 * e.g. "abc123-def456" (always the lexicographically smaller ID first)
 */
export interface PairExplanation {
  /** Canonical pair identifier — sorted user IDs joined by '-' */
  pairKey: string;

  /**
   * 2-3 sentence warm, personalised explanation of why this pair may
   * connect well. Written in Simplified Chinese by the LLM.
   */
  explanation: string;

  /**
   * Archetype chemistry score (0-100) derived from the static
   * chemistryMatrix in archetypeChemistry.ts. Does NOT require an
   * LLM call — computed deterministically before the prompt is built.
   */
  chemistryScore: number;

  /**
   * Interests that both members share (topic IDs or display labels,
   * whichever was used when building the prompt).
   */
  sharedInterests: string[];

  /**
   * Structured connection points detected before the LLM call.
   * Examples: "同乡（广州）", "性格互补（柯基×狐狸）", "深度同好（4个共同深度兴趣）"
   */
  connectionPoints: string[];
}

/**
 * Overall chemistry level for the group, derived from the mean
 * chemistryScore across all pairs.
 *
 * Thresholds (mirrors matchExplanationService logic):
 *   fire  ≥ 85
 *   warm  ≥ 70
 *   mild  ≥ 55
 *   cold  <  55
 */
export type OverallChemistry = 'fire' | 'warm' | 'mild' | 'cold';

/**
 * Full group analysis response returned by
 * GET /api/pool-groups/:groupId/analysis
 *
 * The client can poll this endpoint; it returns immediately from cache
 * after the first generation (7-day TTL per group roster).
 */
export interface GroupAnalysisResponse {
  /** Matches the :groupId URL param */
  groupId: string;

  /** Aggregate chemistry level across all pairs */
  overallChemistry: OverallChemistry;

  /**
   * 1-2 sentence prose description of the group dynamic.
   * Written in Simplified Chinese. Generated deterministically
   * (no LLM call) from archetype composition + avgChemistry.
   */
  groupDynamics: string;

  /**
   * 3-5 personalised ice-breaker topics for this specific group,
   * generated by the LLM (or the deterministic fallback if the LLM
   * is unavailable). Each entry is a single question or prompt in
   * Simplified Chinese, suitable for first-meeting use.
   */
  iceBreakers: string[];

  /**
   * One entry per unique pair in the group (n*(n-1)/2 total).
   * Ordered by pairKey ascending for stable client-side lookup.
   */
  pairExplanations: PairExplanation[];

  /**
   * true  → response was served from the DB cache (no LLM call made)
   * false → fresh generation was performed
   */
  fromCache: boolean;

  /**
   * ISO-8601 timestamp of when this analysis was last generated or
   * refreshed. Clients can display "updated X minutes ago" using this.
   */
  generatedAt: string;
}
