export default defineAppConfig({
  pages: [
    'pages/discover/index',
    'pages/events/index',
    'pages/connections/index',
    'pages/profile/index',
    'pages/index/index',
    'pages/onboarding/onboarding/index',
    'pages/onboarding/personality-test/index',
    'pages/onboarding/essential-data/index',
    'pages/onboarding/extended-data/index',
    'pages/onboarding/profile-review/index',
    'pages/blind-box-payment/index',
    'pages/payment-verification/index',
    'pages/my-events/index',
    'pages/chats/index',
    'pages/journey/index',
    'pages/login/index',
    'pages/terms/index',
    'pages/event-detail/index',
    'pages/event-feedback/index',
    'pages/pool-registration/index',
  ],
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#8B5CF6',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/discover/index',
        text: '发现',
        iconPath: 'assets/tab-icons/discover.png',
        selectedIconPath: 'assets/tab-icons/discover-active.png',
      },
      {
        pagePath: 'pages/events/index',
        text: '活动',
        iconPath: 'assets/tab-icons/events.png',
        selectedIconPath: 'assets/tab-icons/events-active.png',
      },
      {
        pagePath: 'pages/connections/index',
        text: '连接',
        iconPath: 'assets/tab-icons/connections.png',
        selectedIconPath: 'assets/tab-icons/connections-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tab-icons/profile.png',
        selectedIconPath: 'assets/tab-icons/profile-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'JoyJoin',
    navigationBarTextStyle: 'black',
    backgroundColor: '#FAFAFA',
  },
})
