name: Certbot Expand SSL Certificate

on:
  workflow_dispatch:

jobs:
  certbot-expand:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            sudo certbot certonly --nginx --expand -d joyjoinapp.com -d www.joyjoinapp.com -d api.joyjoinapp.com --non-interactive --agree-tos --email ops@joyjoin.com
