/**
 * Confidence calibration module invariants (Plan Item 12).
 *
 * These tests pin the module's contract — purity, monotonicity, M15 verify
 * semantics, artifact shape — without coupling to exact fitted values (the
 * artifact is regenerated by `npm run simulate:calibration`; the pipeline's
 * --check mode catches artifact drift).
 */

import { describe, it, expect } from 'vitest';
import {
  fitCalibration,
  calibrateConfidence,
  expectedTraitAbsError,
  verifyCalibration,
  FITTED_CONFIDENCE_CALIBRATION,
  CALIBRATION_VERSION,
  CALIBRATION_SEED,
  CalibrationRow,
} from '../confidenceCalibration';

function makeRow(meanConfidence: number, correct: 0 | 1, idx: number): CalibrationRow {
  const perTrait = { A: meanConfidence, C: meanConfidence, E: meanConfidence, O: meanConfidence, X: meanConfidence, P: meanConfidence };
  return {
    sessionId: `natural:clean:T${idx}`,
    respondentId: `T${idx}`,
    noise: 'clean',
    arm: 'natural',
    checkpoint: null,
    questionsAnswered: 12,
    meanTraitConfidence: meanConfidence,
    traitConfidences: perTrait,
    traitAbsErrors: { A: 10, C: 10, E: 10, O: 10, X: 10, P: 10 },
    estimatedTop1: correct === 1 ? 'corgi' : 'owl',
    trueArchetype: 'corgi',
    correct,
  };
}

describe('fitCalibration', () => {
  it('produces a monotone non-decreasing correctness curve', () => {
    // Two well-separated regimes: low-confidence rows mostly wrong, high mostly right.
    const rows: CalibrationRow[] = [];
    for (let i = 0; i < 200; i++) rows.push(makeRow(0.6 + (i % 10) * 0.005, i % 5 === 0 ? 1 : 0, i));
    for (let i = 0; i < 200; i++) rows.push(makeRow(0.9 + (i % 10) * 0.005, i % 5 === 0 ? 0 : 1, 1000 + i));
    const fit = fitCalibration(rows, { version: 'test', seed: 1, noiseArms: ['clean'] });
    for (let i = 0; i < fit.correctnessCurve.length - 1; i++) {
      expect(fit.correctnessCurve[i + 1].p).toBeGreaterThanOrEqual(fit.correctnessCurve[i].p);
    }
    // High-confidence regime must calibrate well above the low regime.
    expect(calibrateConfidence(0.92, fit)).toBeGreaterThan(calibrateConfidence(0.62, fit));
  });

  it('is deterministic for identical input', () => {
    const rows = Array.from({ length: 300 }, (_, i) => makeRow(0.5 + (i % 50) * 0.01, i % 2 as 0 | 1, i));
    const a = fitCalibration(rows, { version: 'test', seed: 1, noiseArms: ['clean'] });
    const b = fitCalibration(rows, { version: 'test', seed: 1, noiseArms: ['clean'] });
    expect(JSON.stringify(a)).toBe(JSON.stringify(b));
  });

  it('throws on empty input', () => {
    expect(() => fitCalibration([], { version: 'test', seed: 1, noiseArms: [] })).toThrow();
  });
});

describe('verifyCalibration (M15 semantics)', () => {
  it('passes when observed matches calibrated within tolerance in every n>=50 bin', () => {
    // Perfectly calibrated synthetic set: rows in bin i are correct with
    // probability equal to the bin center, via deterministic pattern.
    const rows: CalibrationRow[] = [];
    for (let bin = 0; bin < 10; bin++) {
      const p = (bin + 0.5) / 10;
      for (let i = 0; i < 100; i++) {
        // calibrateConfidence maps raw->raw when fit on identity-like data;
        // simpler: build rows whose raw confidence equals the target p and
        // correctness matches p, then fit on them.
        rows.push(makeRow(p, i < p * 100 ? 1 : 0, bin * 1000 + i));
      }
    }
    const fit = fitCalibration(rows, { version: 'test', seed: 1, noiseArms: ['clean'] });
    const v = verifyCalibration(rows, fit);
    expect(v.evaluatedBins).toBe(10);
    expect(v.failedBins).toBe(0);
    expect(v.pass).toBe(true);
  });

  it('does not fail on bins below the min-per-bin threshold', () => {
    const rows: CalibrationRow[] = [];
    for (let i = 0; i < 100; i++) rows.push(makeRow(0.9, i < 90 ? 1 : 0, i));
    // 10 rows in a low-confidence bin — must be 'insufficient', never gated.
    for (let i = 0; i < 10; i++) rows.push(makeRow(0.3, 0, 1000 + i));
    const fit = fitCalibration(rows, { version: 'test', seed: 1, noiseArms: ['clean'] });
    const v = verifyCalibration(rows, fit);
    expect(v.bins.some((b) => b.status === 'insufficient')).toBe(true);
    expect(v.pass).toBe(true);
  });

  it('flags a failing bin when observed diverges beyond tolerance', () => {
    // Fit on one population, verify on a shifted one (observed >> calibrated).
    const fitRows = Array.from({ length: 200 }, (_, i) => makeRow(0.9, i < 60 ? 1 : 0, i));
    const fit = fitCalibration(fitRows, { version: 'test', seed: 1, noiseArms: ['clean'] });
    const shifted = Array.from({ length: 200 }, (_, i) => makeRow(0.9, 1, 5000 + i));
    const v = verifyCalibration(shifted, fit);
    expect(v.failedBins).toBeGreaterThan(0);
    expect(v.pass).toBe(false);
  });
});

describe('embedded fitted artifact', () => {
  it('carries the locked version and seed metadata', () => {
    expect(CALIBRATION_VERSION).toBe('v1-20260909');
    expect(CALIBRATION_SEED).toBe(20260909);
    expect(FITTED_CONFIDENCE_CALIBRATION.version).toBe(CALIBRATION_VERSION);
    expect(FITTED_CONFIDENCE_CALIBRATION.fittedOnSeed).toBe(CALIBRATION_SEED);
  });

  it('has non-empty monotone correctness curve and decreasing trait-error curve', () => {
    const { correctnessCurve, traitErrorCurve } = FITTED_CONFIDENCE_CALIBRATION;
    expect(correctnessCurve.length).toBeGreaterThan(0);
    expect(traitErrorCurve.length).toBeGreaterThan(0);
    for (let i = 0; i < correctnessCurve.length - 1; i++) {
      expect(correctnessCurve[i + 1].p).toBeGreaterThanOrEqual(correctnessCurve[i].p - 1e-9);
    }
    const first = traitErrorCurve[0];
    const last = traitErrorCurve[traitErrorCurve.length - 1];
    expect(last.p).toBeLessThanOrEqual(first.p + 1e-9);
  });

  it('calibrates inflated raw confidence down toward observed agreement', () => {
    // Baseline fact the artifact must encode: raw ~0.9 does NOT mean 90% correct.
    const calibrated = calibrateConfidence(0.9, FITTED_CONFIDENCE_CALIBRATION);
    expect(calibrated).toBeLessThan(0.65);
    expect(calibrated).toBeGreaterThan(0.1);
    const err = expectedTraitAbsError(0.9, FITTED_CONFIDENCE_CALIBRATION);
    expect(err).toBeGreaterThan(5);
    expect(err).toBeLessThan(20);
  });

  it('calibrateConfidence stays within [0,1] for out-of-range input', () => {
    expect(calibrateConfidence(-0.5, FITTED_CONFIDENCE_CALIBRATION)).toBeGreaterThanOrEqual(0);
    expect(calibrateConfidence(1.5, FITTED_CONFIDENCE_CALIBRATION)).toBeLessThanOrEqual(1);
  });
});
